spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gadget-testdb
    username: gadget
    password: gadget123

server:
  port: 8081

logging:
  level:
    org:
      springframework: DEBUG 

  
